icon_url: https://raw.githubusercontent.com/FelipeVasquez350/Custom-Truenas-Catalog/main/charts/lucius-v/1.0.0/icon.png
categories:
  - productivity
screenshots:
  - https://raw.githubusercontent.com/FelipeVasquez350/Custom-Truenas-Catalog/main/charts/lucius-v/1.0.0/screenshot_1.png
tags:
  - bot