image:  
  pullPolicy: IfNotPresent
  repository: ghcr.io/felipevasquez350/quartz-config
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

quartzConfig:
  additionalEnvs: []

quartzRunAs:
  user: 1000
  group: 1000

quartzStorage:
  content:
    type: ixVolume
    ixVolumeConfig:
      datasetName: content
  additionalStorages: []