image:  
  pullPolicy: IfNotPresent
  repository: ghcr.io/felipevasquez350/quartz-config
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

quartzConfig:
  additionalEnvs: []

quartzRunAs:
  user: 0
  group: 0

quartzNetwork:
  webPort: 59980
  hostNetwork: false
  
quartzStorage:
  content:
    type: ixVolume
    ixVolumeConfig:
      datasetName: content
  additionalStorages: []