image:
  repository: node
  pullPolicy: IfNotPresent
  tag: 20.9.0-alpine3.18

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

ctpbotConfig:
  additionalEnvs: []
ctpbotRunAs:
  user: 568
  group: 568
ctpbotStorage:
  archive:
    type: ixVolume
    datasetName: archive
  additionalStorages: []