{{- include "ix.v1.common.loader.init" . -}}

{{/* Merge the templates with Values */}}
{{- $_ := mustMergeOverwrite .Values (include "luciusvii.workload" $ | fromYaml) -}}

{{- include "ix.v1.common.loader.apply" . -}}